# Generated by Django 2.1.5 on 2019-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190125_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
